CREATE TABLE City
(
Id INT IDENTITY,
CONSTRAINT PK_City PRIMARY KEY(Id),
NameCity NVARCHAR(20) NOT NULL,
Id_Country INT NOT NULL,
CONSTRAINT FK_Country FOREIGN KEY (Id_Country) REFERENCES Country(Id)
);