CREATE TABLE Guest (
Id INT IDENTITY,
CONSTRAINT PK_Guest PRIMARY KEY(Id),
Passport NVARCHAR(10),
FirstName NVARCHAR(20) NOT NULL,
LastName NVARCHAR(20) NOT NULL,
MiddleName NVARCHAR(20),
DOB DATE NOT NULL,
Sex VARCHAR(1) NOT NULL,
CONSTRAINT CK_Guest_Sex CHECK(Sex='M' OR Sex='F'),
VipGuestStatus BIT,
Discont INT DEFAULT 0
);